### PR TITLE
Fixup infrastructure issues

### PR DESCRIPTION
**Pull request by hugodahl**
Fix the following:
* Missing licenses
* GitHub actions for missing docs

### CODE REVIEW

**Comment by hugodahl** [comment]
Addresses the issues which caused the build action to fail in PR #1

**Comment by brentru** [comment]
@hugodahl I made this repo a 2yrs for a specific implementation I expected to work on, but it wasn't necessary.

@ladyada  Should we just delete this lib. so people stop spending time updating it?

**Comment by tannewt** [comment]
Don't delete any repos. You can archive them though.

**Comment by brentru** [comment]
@tannewt  Right, thanks. Could I go thru the archive process for this repo since there's no code in here?

**Comment by tannewt** [comment]
I didn't realize it is empty. I'll just delete it.

**Comment by tannewt** [comment]
Actually, that'd make everything disappear. I'll just archive.

**Pull request closed without merging**
